# Generated by Django 4.0 on 2021-12-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
    ]
